fix: use updateProductVariantPrices mutation to save variant price
reactioncommerce/reaction-admin pull request #172
Opened 2020-01-07 05:42 UTC by trojanh

Signed-off-by: trojanh <rajan.tiwari@kiprosh.com>

Resolves https://github.com/reactioncommerce/reaction-admin/issues/170
Impact: **breaking|major**  
Type: **bugfix**

## Issue
Please provide starting context, i.e. logged in as a user, configure a particular payment method.

1. Create a new variant.
2. Add a price to it
3. Refresh to see that the price is reset to zero.

## Solution
Use  `updateProductVariantPrices` mutation to set the price.

## Breaking changes
none

## Testing
1. Create a new variant.
2. Add a price to it
3. Refresh to see that the price is NOT reset to zero.

2020-01-08 18:15 UTC, spencern commented
Thanks for the PR!

2020-01-08 23:50 UTC, willopez requested changes
One small change necesary, otherwise looks good.

2020-01-08 23:50 UTC, willopez commented on imports/plugins/included/product-admin/client/hocs/withVariantForm.js
> +        Alerts.toast(i18next.t("productDetailEdit.updateProductFieldFail", { [fieldName]: value }), "error");
For new code we want to use the new notification library `notistack` as seen here: https://github.com/reactioncommerce/reaction-admin/blob/e9cc890e3a1b63cec0804b260a161ed60f685a79/imports/plugins/core/taxes/client/containers/GeneralTaxSettings.js#L31 Please update to use it.

2020-01-09 19:34 UTC, manueldelreal commented
Save for @willopez review comment and the linting errors on the checks this one does permit the price update via the admin ui.

2020-01-10 13:36 UTC, trojanh commented
@willopez I have replaced all occurrences of `Alerts.alert` and `Alert.toast` to use `snackbar`. Also, fixed the linting error and rebased the branch. Please review the changes.

2020-01-10 19:32 UTC, willopez commented
thanks @trojanh!

2020-01-10 19:32 UTC, merged