Fix: Tags not rendering without manual refresh
reactioncommerce/reaction-admin pull request #338
Opened 2021-01-22 21:18 UTC by jrw421

Signed-off-by: Jess Wolvington jess.wolvington@gmail.com

Resolves #287 
Impact: **minor**
Type: **bugfix**

## Issue
When adding a tag to products via the multiple items operation, the tag does not show up in the product detail screen until you modify the record or manually refresh the page

To reproduce the issue: 
1. Navigate to the Products tab.
2. Select several products.
2. Choose "Add/Remove Tags" from the `Actions` dropdown.
3. Navigate to the detail page for one of the newly tagged products.
4. Observe the just-added tags do not appear.
5. Refresh page, observe the newly added tag appears.

## Solution
This bug can be fixed with a simple refreshProduct invocation prior to mapping through the tag nodes. Previously the tag nodes had not been refreshed prior to entering the detail page, thus hadn't been fetched at that point. Refetching the product data before mapping the tag nodes will ensure the data is there before the nodes are mapped.

## Breaking changes
None

## Testing
1. Navigate to the Products tab.
2. Select several products.
2. Choose "Add/Remove Tags" from the `Actions` dropdown.
3. Click to enter detail page for one of the newly tagged products.
4. Observe the just-added tags appear without any further action (previously the user would have had to refresh the page manually).

2021-01-25 14:57 UTC, focusaurus approved these changes

2021-01-25 16:30 UTC, Akarshit requested changes
@jrw421  Adding this here would cause the product to be re-fetched every-time the form is rendered, right?
Would it make sense to only update the product only if a new tag was added. Or only fetch the product once when navigating to the product page and re-fetching when tag is added?

2021-01-26 17:38 UTC, jrw421 commented
> @jrw421 Adding this here would cause the product to be re-fetched every-time the form is rendered, right?
> Would it make sense to only update the product only if a new tag was added. Or only fetch the product once when navigating to the product page and re-fetching when tag is added?

@Akarshit, that’s a good point! That was something I had originally considered but in looking closer, since the tag operation is a bulk update on the product table, refetchProduct from the useProduct hook would have to be called for each product that needed to be updated (tag added or deleted). 

This complicates things somewhat because the useProduct hook parses the product information (productId, variantId, optionId, shopId) from the routeParams on the product page, which aren’t accessible from the product table (where the bulk tag operations occur). 

Refreshing each page from within the tag selector from the product table would only be possible with refactoring and getting each updated product’s information, passing it to the useProduct hook, and refreshing each product’s page from there. Based off of that, I’m not seeing a clean approach of refetching for each updated product only on add/delete of a tag, other than simply refetch the product’s data when the tag component was rendered - but definitely happy to talk through any efficient/better approaches! 😊

2021-01-27 19:13 UTC, Akarshit commented
@jrw421 So if the expectation is that we only need to update the tags once the page is refreshed, can we use `useEffect` and only fetch the product on the initial render?

2021-01-28 01:08 UTC, jrw421 commented
> @jrw421 So if the expectation is that we only need to update the tags once the page is refreshed, can we use `useEffect` and only fetch the product on the initial render?

@Akarshit Oh, I see what you're saying now - yes, absolutely, good call.

2021-01-28 03:33 UTC, Akarshit requested changes
Yes I was thinking something like this. But, I still think this would still refetch the products every-time the component is rendered.
Should we use something like this instead:
```
useEffect(() => {
  refetchProduct();
}, []);
```

2021-01-28 03:46 UTC, jrw421 commented
> Yes I was thinking something like this. But, I still think this would still refetch the products every-time the component is rendered.
> Should we use something like this instead:
> 
> ```
> useEffect(() => {
>   refetchProduct();
> }, []);
> ```

Hmm I suppose, but don't we still want a rerender on an update from the component? Including the array would limit the renrender to only the initial load I believe.

2021-01-28 03:50 UTC, Akarshit commented
If by re-render on update you are suggesting that adding a tag on the admin page should trigger a refetch of the products, I see that is being handled [here](https://github.com/reactioncommerce/reaction-admin/blob/54b05dab356b466367828413cb36302b1d0e07e5/imports/plugins/included/product-admin/client/blocks/ProductTagForm.js#L71).
Including the empty array would limit the refetch to happen on the initial load. 
Or am I missing something?

2021-01-28 03:58 UTC, jrw421 commented
> If by re-render on update you are suggesting that adding a tag on the admin page should trigger a refetch of the products, I see that is being handled [here](https://github.com/reactioncommerce/reaction-admin/blob/54b05dab356b466367828413cb36302b1d0e07e5/imports/plugins/included/product-admin/client/blocks/ProductTagForm.js#L71).
> Including the empty array would limit the refetch to happen on the initial load.
> Or am I missing something?

I see what you're saying. The TagSelector [here](https://github.com/reactioncommerce/reaction-admin/blob/54b05dab356b466367828413cb36302b1d0e07e5/imports/plugins/included/product-admin/client/components/ProductsTable.js#L449) rendered from the ProductsTable doesn't have the same onSuccess fired off, but having the rerender called once on page load should do the trick there. So yes, I do agree that we should only need the initial call.

2021-01-29 02:44 UTC, Akarshit approved these changes

2021-01-29 15:50 UTC, merged