allow empty strings in shopURL
reactioncommerce/reaction-admin pull request #339
Opened 2021-01-26 18:41 UTC by Akarshit

Resolves #291 
Impact: **minor**
Type: **bugfix**

## Issue
The SimpleSchema was cleaning the object of empty string before saving it. Also the RegEx was not allowing empty strings to pass.

## Solution
1. Configured cleaning to not remove empty strings.
2. Modified regex to allow empty string.

## Breaking changes
None expected

## Testing
1. Login as Admin
2. Enter a URL for the store logo and save it. The top left icon should update based on the URL you entered
3. Remove the URL and hit Save, the logo should default back to the Reaction Commerce logo.

2021-01-27 15:09 UTC, nnnnat commented
@Akarshit can you sign your commit and force push?

2021-01-27 15:11 UTC, Akarshit commented
Yup, will do that.

On Wed, Jan 27, 2021 at 8:10 AM Nat Hamilton <notifications@github.com>
wrote:

> @Akarshit <https://github.com/Akarshit> can you sign your commit and
> force push?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/reactioncommerce/reaction-admin/pull/339#issuecomment-768350567>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB3HFLPADDYNDY3W7EKV23LS4AUFJANCNFSM4WT5QR3Q>
> .
>

2021-01-28 16:05 UTC, jrw421 requested changes

2021-01-28 16:05 UTC, jrw421 commented on imports/plugins/core/dashboard/client/components/ShopLogoUrls.js
> +    optional: true,
Tested locally and works as advertised 🎉 Can we remove this trailing comma? Looks like that isn't the convention for the rest of the file.

2021-01-28 17:52 UTC, jrw421 approved these changes
Looks good to me.

2021-02-12 19:11 UTC, Akarshit commented
Only updated the commit message.

2021-02-12 19:30 UTC, merged